djangovue_porta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("inmobiliaria_porta.urls"))
]

inmobiliaria_porta/forms.py
from django import forms
from .models import *
class ViviendaForm(forms.ModelForm):
    fechaInicio = forms.DateField(label='Fecha Inicio', widget=forms.DateInput(attrs={'type': 'date'}))
    fechaTermino = forms.DateField(label='Fecha Fin', widget=forms.DateInput(attrs={'type': 'date'}))
    titulo = forms.CharField(label='Título', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe el título de la propiedad'}))
    cometario = forms.CharField(label='Comentario', widget=forms.Textarea(attrs={'maxlength': 800, 'placeholder': 'Escribe un comentario sobre la propiedad'}))
    tipoVivienda = forms.ChoiceField(label='Tipo de vivienda', choices=[('Departamento', 'Departamento'), ('Vivienda', 'Vivienda')])

    usoActual = forms.CharField(label='Uso Actual', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe el uso actual de la propiedad'}))
    usoPermitido = forms.CharField(label='Uso Permitido', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe el uso permitido de la propiedad'}))
    condicionFisica = forms.CharField(label='Condición Física', widget=forms.Textarea(attrs={'maxlength': 800, 'placeholder': 'Describe la condición física de la propiedad'}))
    claseInmueble = forms.CharField(label='Clase de Inmueble', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe la clase de inmueble de la propiedad'}))
    numeroFrentes = forms.IntegerField(label='Número de Frentes', widget=forms.NumberInput(attrs={'min': 0}))
    medidaTerreno = forms.CharField(label='Medida del Terreno', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe la medida de la propiedad'}))
    m2Terreno = forms.CharField(label='M2 del Terreno', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe los m2 de la propiedad'}))
    construccionN1 = forms.CharField(label='Construcción N1', max_length=100, widget=forms.TextInput(attrs={'placeholder': '8'}))
    construccionN2 = forms.CharField(label='Construcción N2', max_length=100, widget=forms.TextInput(attrs={'placeholder': '8'}))
    construccionN3 = forms.CharField(label='Construcción N3', max_length=100, widget=forms.TextInput(attrs={'placeholder': '8'}))
    gravamen = forms.CharField(label='Gravamen', max_length=100, widget=forms.TextInput(attrs={'placeholder': '8'}))
    valorGravamen = forms.CharField(label='Valor de Gravamen', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe el valor del gravamen'}))
    valorSegunAvaluo = forms.CharField(label='Valor según Avalúo', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe el valor según avalúo'}))
    operacion = forms.CharField(label='Operación', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe la operación'}))
    condicionPago = forms.CharField(label='Condición de Pago', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe la condición de pago'}))
    escrituracion = forms.CharField(label='Escrituración', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe la escrituración'}))
    avaluo = forms.CharField(label='Avalúo', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe el avalúo de la propiedad'}))
    impuestos = forms.CharField(label='Impuestos', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe los impuestos de la propiedad'}))
    otros = forms.CharField(label='Otros', widget=forms.Textarea(attrs={'maxlength': 400, 'placeholder': 'Escribe otros detalles de la propiedad'}))
    total = forms.CharField(label='Total', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe el total de la propiedad'}))

    precioVenta = forms.CharField(label='Precio de Venta', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe el precio de venta de la propiedad'}))
    precioRenta = forms.CharField(label='Precio de Renta', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe el precio de renta de la propiedad'}))
    precioMinimo = forms.CharField(label='Precio Mínimo', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe el precio mínimo de la propiedad'}))
    precioPromedio = forms.CharField(label='Precio Promedio', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe el precio promedio de la propiedad'}))
    precioMaximo = forms.CharField(label='Precio Máximo', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe el precio máximo de la propiedad'}))
    comision1 = forms.CharField(label='Comisión1', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe la comisión de la propiedad'}))
    ganancia1 = forms.CharField(label='Ganancia1', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe la ganancia de la propiedad'}))
    comision2 = forms.CharField(label='Comisión2', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe la comisión de la propiedad'}))
    ganancia2 = forms.CharField(label='Ganancia2', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe la ganancia de la propiedad'}))
    exclusivo= forms.CharField(label='exclivo', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe el exclusivo'}))
    disponibilidad = forms.ChoiceField(label='Tipo de Disponibilidad', choices=[('Disponibilidad', 'Disponibilidad'), ('Exclusividad', 'Exclusividad')])

    empresa = forms.CharField(label='Empresa', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe la empresa'}))
    agente = forms.CharField(label='Agente', max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Escribe el agente'}))
    propietario = forms.CharField(label='Propietario', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Escribe el propietario'}))
    claveCastratal = forms.CharField(label='Clave Catastral', max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Escribe la clave catastral'}))
    lote = forms.CharField(label='Lote', max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Escribe el lote'}))
    manzana = forms.CharField(label='Manzana', max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Escribe la manzana'}))
    cuentaAgua = forms.BooleanField(label='Cuenta de Agua', required=False)
    ocultarDir = forms.BooleanField(label='Ocultar Dirección', required=False)
    aceptaInfonavid = forms.BooleanField(label='Acepta Infonavit', required=False)
    aceptaFovisste = forms.BooleanField(label='Acepta Fovisste', required=False)

    propietario = forms.CharField(label='Propietario', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe al propietario'}))
    lote = forms.CharField(label='Lote', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe el lote'}))
    manzana = forms.CharField(label='Manzana', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe la manzana'}))
    cuentaAgua = forms.BooleanField(label='Cuenta con Agua', required=False)
    autosEst = forms.IntegerField(label='Autos Estacionados', widget=forms.NumberInput(attrs={'min': 0}))
    autosIndep = forms.IntegerField(label='Autos Independientes', widget=forms.NumberInput(attrs={'min': 0}))
    estacionamiento = forms.CharField(label='Estacionamiento', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe el estacionamiento'}))
    cocheraElectrica = forms.CharField(label='Cochera Electrica', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe la cochera electrica'}))
    patio = forms.CharField(label='Patio', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe el patio'}))
    asador = forms.CharField(label='Asador', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe el asador'}))
    fuentes = forms.CharField(label='Fuentes', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe la fuente'}))
    jacuzzi = forms.CharField(label='Jacuzzi', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe el jacuzzi'}))
    alberca = forms.CharField(label='Alberca', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe la alberca'}))
    jardin = forms.CharField(label='Jardin', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe el jardin'}))
    bodega = forms.CharField(label='Bodega', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe la bodega'}))
    cisterna = forms.CharField(label='Cisterna', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe la cisterna'}))
    tinaco = forms.CharField(label='Tinaco', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe el tinaco'}))
    acCentral = forms.BooleanField(label='Aire central', required=False)
    proteccionVentana = forms.BooleanField(label='Proteccion ventana', required=False)
    persianaCortina = forms.BooleanField(label='Persiana cortina', required=False)
    hidroneumatico = forms.BooleanField(label='Hidroneumatico', required=False)
    amueblado = forms.BooleanField(label='Amueblado', required=False)
    piso1 = forms.CharField(label='Piso1', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe el piso'}))
    piso2 = forms.CharField(label='Piso2', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe el piso'}))
    piso3 = forms.CharField(label='Piso3', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe el piso'}))
    alarma = forms.BooleanField(label='Alarma', required=False)
    uriGoogleMaps = forms.CharField(label='Urigooglemaps', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe '}))
    cocinaIntegral = forms.CharField(label='Cocina Integral', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe la cocina integral'}))
    vitropiso = forms.CharField(label='Vitropis', max_length=60, widget=forms.TextInput(attrs={'placeholder': 'Escribe el vitropiso'}))

templates/ProprietyInfoView.html
{% extends "baseDjango.html" %}
{% load static %}
{% block head %}
    <title>Detalles propiedad | Porta</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/propriedades/proprietyInfo.css' %}">
{% endblock %}
{% block content %}
<div class="property-info-view">
    <h2>Información de la Propiedad</h2>
    <div v-if="property">
      <div class="property-images">
    <img src="{{ vivienda.imagen }}" alt="Property Image">
  </div>
   <div class="buttons">
      <button class="btn-editar" onclick="redirectTo('/editar/{{ vivienda.id }}')">Editar</button>
      <button class="btn-eliminar" onclick="redirectTo('/eliminarVivienda/{{ vivienda.id }}')">Eliminar</button>
  </div>
  <h3>{{ vivienda.titulo }}</h3>
  <p>Precio: ${{ vivienda.precioVenta }}</p>
  <!-- Mostrar las imágenes de la propiedad -->
  <!-- Otros detalles de la propiedad -->
  <h4>Fechas</h4>
  <p>Fecha Inicio: {{ vivienda.fechaInicio }}</p>
  <p>Fecha Fin: {{ vivienda.fechaTermino }}</p>
  <!-- Sección de información de la propiedad -->
  <h4>Información de la Propiedad</h4>
  <p>Título: {{ vivienda.titulo }}</p>
  <p>Comentario: {{ vivienda.cometario }}</p>
  <p>Tipo de vivienda: {{ vivienda.tipoVivienda }}</p>
  <p>Uso Actual: {{ vivienda.usoActual }}</p>
  <p>Uso Permitido: {{ vivienda.usoPermitido }}</p>
  <p>Condición Física: {{ vivienda.condicionFisica }}</p>
  <p>Clase de Inmueble: {{ vivienda.claseInmueble }}</p>
  <p>Número de Frentes: {{ vivienda.numeroFrentes }}</p>
  <p>Medida del Terreno: {{ vivienda.medidaTerreno }}</p>
  <p>M2 del Terreno: {{ vivienda.m2Terreno }}</p>
  <p>Construcción N1: {{ vivienda.construccionN1 }}</p>
  <p>Construcción N2: {{ vivienda.construccionN2 }}</p>
  <p>Construcción N3: {{ vivienda.construccionN3 }}</p>
  <p>Gravamen: {{ vivienda.gravamen }}</p>
  <p>Valor de Gravamen: {{ vivienda.valorGravamen }}</p>
  <p>Valor según Avalúo: {{ vivienda.valorAvaluo }}</p>
  <p>Operación: {{ vivienda.operacion }}</p>
  <p>Condición de Pago: {{ vivienda.condicionPago }}</p>
  <p>Escrituración: {{ vivienda.escrituracion }}</p>
  <p>Avalúo: {{ vivienda.avaluo }}</p>
  <p>Impuestos: {{ vivienda.impuestos }}</p>
  <p>Otros: {{ vivienda.otros }}</p>
  <p>Total: {{ vivienda.total }}</p>
  <!-- Sección de precios y comisiones -->
  <h4>Precios y comisiones</h4>
  <p>Precio de Venta: {{ vivienda.precioVenta }}</p>
  <p>Precio de Renta: {{ vivienda.precioRenta }}</p>
  <p>Precio Mínimo: {{ vivienda.precioMinimo }}</p>
  <p>Precio Promedio: {{ vivienda.precioPromedio }}</p>
  <p>Precio Máximo: {{ vivienda.precioMaximo }}</p>
  <p>Comisión1: {{ vivienda.comision1 }}</p>
  <p>Ganancia1: {{ vivienda.ganancia1 }}</p>
  <p>Comisión2: {{ vivienda.comision2 }}</p>
  <p>Ganancia2: {{ vivienda.ganancia2 }}</p>
  <!-- Sección de disponibilidad y exclusividad -->
  <h4>Disponibilidad y exclusividad</h4>
  <p>Tipo de Disponibilidad: {{ vivienda.tipoDisponibilidad }}</p>
  <!-- Sección de información de la transacción de la propiedad -->
  <h4>Información de la transacción de la propiedad</h4>
  <p>Empresa: {{ vivienda.empresa }}</p>
  <p>Agente: {{ vivienda.agente }}</p>
  <p>Propietario: {{ vivienda.propietario }}</p>
  <p>Clave Catastral: {{ vivienda.claveCastratal }}</p>
  <p>Lote: {{ vivienda.lote }}</p>
  <p>Manzana: {{ vivienda.manzana }}</p>
  <p>Cuenta de Agua: {{ vivienda.cuentaAgua }}</p>
  <p>Ocultar Dirección: {{ vivienda.ocultarDir }}</p>
  <p>Acepta Infonavit: {{ vivienda.aceptaInfonavit }}</p>
  <p>Acepta Fovisste: {{ vivienda.aceptaFovisste }}</p>
  <p>Autos Estacionados: {{ vivienda.autosEst }}</p>
  <p>Autos Independientes: {{ vivienda.autosIndep }}</p>
  <p>Estacionamiento: {{ vivienda.estacionamiento }}</p>
  <p>Cochera Eléctrica: {{ vivienda.cocheraElectrica }}</p>
  <p>Patio: {{ vivienda.patio }}</p>
  <p>Asador: {{ vivienda.asador }}</p>
  <p>Fuentes: {{ vivienda.fuentes }}</p>
  <p>Jacuzzi: {{ vivienda.jacuzzi }}</p>
  <p>Alberca: {{ vivienda.alberca }}</p>
  <p>Jardín: {{ vivienda.jardin }}</p>
  <p>Bodega: {{ vivienda.bodega }}</p>
  <p>Cisterna: {{ vivienda.cisterna }}</p>
  <p>Tinaco: {{ vivienda.tinaco }}</p>
  <p>Aire Central: {{ vivienda.acCentral }}</p>
  <p>Protección de Ventana: {{ vivienda.proteccionVentana }}</p>
  <p>Persiana Cortina: {{ vivienda.persianaCortina }}</p>
  <p>Hidroneumático: {{ vivienda.hidroneumatico }}</p>
  <p>Patio Encementado: {{ vivienda.patioEncementado }}</p>
  <p>Cocina Integral: {{ vivienda.cocinaIntegral }}</p>
  <p>Amueblado: {{ vivienda.amueblado }}</p>
  <p>Piso 1: {{ vivienda.piso1 }}</p>
  <p>Piso 2: {{ vivienda.piso2 }}</p>
  <p>Piso 3: {{ vivienda.piso3 }}</p>
  <p>Alarma: {{ vivienda.alarma }}</p>
  <p>URL Google Maps: {{ vivienda.urlGoogleMap }}</p>
  <p>Tipo de Vitropiso: {{ vivienda.vitropiso }}</p>
  <p>Closet: {{ vivienda.closet }}</p>
  <p>Barda: {{ vivienda.barda }}</p>
  <p>Equipada: {{ vivienda.equipada }}</p>
  <!-- Sección de ubicación -->
  <h4>Ubicación</h4>
  <p>País: {{ vivienda.pais }}</p>
  <p>Estado: {{ vivienda.estado }}</p>
  <p>Municipio: {{ vivienda.municipio }}</p>
  <p>Ciudad: {{ vivienda.ciudad }}</p>
  <p>Colonia: {{ vivienda.colonia }}</p>
  <p>Código Postal: {{ vivienda.codigoPostal }}</p>
  <p>Calle: {{ vivienda.calle }}</p>
  <p>Número Exterior: {{ vivienda.numExterior }}</p>
  <p>Número Interior: {{ vivienda.numInterior }}</p>
  <p>Entre calle 1: {{ vivienda.entreCalle1 }}</p>
  <p>Entre calle 2: {{ vivienda.entreCalle2 }}</p>
  <p>Nombre Complejo: {{ vivienda.nombreComplejo }}</p>
</div>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% block html %}
<html lang="en">
<head>
{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}{% endblock%} | Porta</title>
{% endblock %}
</head>
<body>
    {% block body %}
    {% block main %}{% endblock%}
    {% endblock %}
</body>
</html>
{% endblock %}

templates/baseVue.html
{% extends 'base.html' %}

{% block html %}
<html>
<head>
  {% block head %}{{ block.super}}{% endblock %}
<script defer src="http://localhost:8080/js/chunk-vendors.js"></script><script defer src="http://localhost:8080/js/app.js"></script></head>
<body>
{% block body %}
  {{ block.super}}
  <noscript>
    <strong>
      Weererasfdhjkaslfajsflk
    </strong>
  </noscript>  
  <div id="app"></div>
  <!-- built files will be auto injected -->
{% endblock body %}
</body>
</html>
{% endblock html %}

templates/proprietyCreate.html
{% extends 'baseDjango.html' %}
{% load static %}

{% block head %}
<title>Crear | Porta</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/propriedades/proprietyCreate.css' %}">
{% endblock %}

{% block content %}

<div>
  <form method="post">
    {% csrf_token %}
    <section>
      <h3>Fechas</h3>
      <label for='id_fechaInicio'>Fecha Inicio: </label>
      {{ form.fechaInicio }}

      <label for="fechaFin">Fecha Fín:</label>
      {{ form.fechaTermino}}
    </section>

    <!-- ######### seccion de informacion de la propiedad ######## -->
    <section>
      <h3>Información de la propiedad:</h3>
      <label for="titulo">Título:</label>
      {{ form.titulo }}

      <label for="comentario">Comentario:</label>
      {{ form.cometario }}

      <label for="tipoVivienda">Tipo de vivienda:</label>
      {{ form.tipoVivienda }}

      <label for="usoActual">Uso Actual:</label>
      {{ form.usoActual }}

      <label for="usoPermitido">Uso Permitido:</label>
      {{ form.usoPermitido }}

      <label for="condicionFisica">Condición Física:</label>
      {{ form.condicionFisica }}

      <label for="claseInmueble">Clase de Inmueble:</label>
      {{ form.claseInmueble }}

      <label for="numeroFrentes">Número de Frentes:</label>
      {{ form.numeroFrentes }}

      <label for="medidaTerreno">Medida del Terreno:</label>
      {{ form.medidaTerreno }}

      <label for="m2Terreno">M2 del Terreno:</label>
      {{ form.m2Terreno }}

      <label for="construccionN1">Construccion N1:</label>
      {{ form.construccionN1 }}

      <label for="construccionN2">Construccion N2:</label>
      {{ form.construccionN2 }}

      <label for="construccionN3">Construccion N3:</label>
      {{ form.construccionN3 }}

      <label for="gravamen">Gravamen:</label>
      {{ form.gravamen }}
      <!-- ######### En duda ######## -->
      <label for="valorGravamen">Valor de Gravamen:</label>
      {{ form.valorGravamen }}

      <label for="valorAvaluo">Valor segun Avaúo:</label>
      {{ form.valorSegunAvaluo }}

      <label for="operacion">Operación:</label>
      {{ form.operacion }}

      <label for="condicionPago">Condición de Pago:</label>
      {{ form.condicionPago }}

      <label for="escrituracion">Escrituración:</label>
      {{ form.escrituracion }}

      <label for="avaluo">Avalúo:</label>
      {{ form.avaluo }}

      <label for="impuestos">Impuestos:</label>
      {{ form.impuestos }}

      <label for="otros">Otros:</label>
      {{ form.otros }}

      <label for="total">Total:</label>
      {{ form.total }}
    </section>

    <!-- ######### seccion de precios y comisiones ######## -->
    <section>
      <h3>Precios y comisiones</h3>
      <label for="precioVenta">Precio de Venta:</label>
      {{ form.precioVenta }}

      <label for="precioRenta">Precio de Renta:</label>
      {{ form.precioRenta }}

      <label for="precioMinimo">Precio Minimo:</label>
      {{ form.precioMinimo }}

      <label for="precioPromedio">Precio Promedio:</label>
      {{ form.precioPromedio }}

      <label for="precioMaximo">Precio Maximo:</label>
      {{ form.precioMaximo }}

      <label for="comision1">Comision1:</label>
      {{ form.comision1 }}

      <label for="ganancia1">Ganancia1:</label>
      {{ form.ganancia1 }}

      <label for="comision2">Comision2:</label>
      {{ form.comision2 }}

      <label for="ganancia2">Ganancia2:</label>
      {{ form.ganancia2 }}
    </section>

    <!-- ######### seccion de la disponibilidad y exclusividad ######## -->
    <section>
      <h3>Disponibilidad y exclusividad</h3>
      {{ form.disponibilidad }}
      <label for="exclusivo">Exclusivo</label>
      {{ form.exclusivo }}
    </section>
    <!-- ######### seccion de la transaccion de la propiedad ######## -->
    <section>
      <h3>Información de la transacción de la propiedad</h3>
      <label for="empresa">Empresa:</label>
      {{ form.empresa }}

      <label for="agente">Agente:</label>
      {{ form.agente }}

      <label for="propietario">Propietario:</label>
      {{ form.propietario }}

      <label for="claveCastratal">Clave Catastral:</label>
      {{ form.claveCastratal }}

      <label for="lote">Lote:</label>
      {{ form.lote }}

      <label for="manzana">Manzana:</label>
      {{ form.manzana }}

      <label for="cuentaAgua">Cuenta de Agua:</label>
      {{ form.cuentaAgua }}

      <label for="ocultarDir">Ocultar Dirección:</label>
      {{ form.ocultarDir }}

      <label for="aceptaInfonavid">Acepta Infonavit:</label>
      {{ form.aceptaInfonavid }}

      <label for="aceptaFovisste">Acepta Fovisste:</label>
      {{ form.aceptaFovisste }}

      <label for="autosEst">Autos Estacionados:</label>
      {{ form.autosEst }}

      <label for="autosIndep">Autos Independientes:</label>
      {{ form.autosIndep }}

      <label for="estacionamiento">Estacionamiento:</label>
      {{ form.estacionamiento }}

      <label for="cocheraElectrica">Cochera Eléctrica:</label>
      {{ form.cocheraElectrica }}

      <label for="patio">Patio:</label>
      {{ form.patio }}

      <label for="asador">Asador:</label>
      {{ form.asador }}

      <label for="fuentes">Fuentes:</label>
      {{ form.fuentes }}

      <label for="jacuzzi">Jacuzzi:</label>
      {{ form.jacuzzi }}

      <label for="alberca">Alberca:</label>
      {{ form.alberca }}

      <label for="jardin">Jardín:</label>
      {{ form.jardin }}

      <label for="bodega">Bodega:</label>
      {{ form.bodega }}

      <label for="cisterna">Cisterna:</label>
      {{ form.cisterna }}

      <label for="tinaco">Tinaco:</label>
      {{ form.tinaco }}

      <label for="acCentral">Aire Central:</label>
      {{ form.acCentral }}

      <label for="proteccionVentana">Protección de Ventana:</label>
      {{ form.proteccionVentana }}

      <label for="persianaCortina">Persiana Cortina:</label>
      {{ form.persianaCortina }}

      <label for="hidroneumatico">Hidroneumático:</label>
      {{ form.hidroneumatico }}

      <label for="patioEncementado">Patio Encementado:</label>
      {{ form.patioEncementado }}

      <label for="cocinaIntegral">Cocina integral:</label>
      {{ form.cocinaIntegral }}

      <label for="amueblado">Amueblado:</label>
      {{ form.amueblado }}

      <label for="piso1">Piso 1:</label>
      {{ form.piso1}}

      <label for="piso2">Piso 2:</label>
      {{ form.piso2}}

      <label for="piso3">Piso 3:</label>
      {{ form.piso3}}

      <label for="alarma">Alarma:</label>
      {{ form.alarma}}

      <label for="uriGoogleMap">URL Google Maps:</label>
      {{ form.uriGoogleMaps}}

      <label for="vitropiso">Tipo de Vitropiso:</label>
      {{ form.vitropiso}}

      <label for="closet">Closet:</label>
      {{ form.closet}}

      <label for="barda">Barda:</label>
      {{ form.barda}}

      <label for="equipada">Equipada:</label>
      {{ form.equipada}}
    </section>

    <!-- ######### seccion de la ubicacion ######## -->
    <section>
      <h3>Ubicación</h3>
      <label for="pais">País:</label>
      {{ form.pais}}

      <label for="estado">Estado:</label>
      {{ form.estado}}

      <label for="municipio">Municipio:</label>
      {{ form.municipio}}

      <label for="ciudad">Ciudad:</label>
      {{ form.ciudad}}

      <label for="colonia">Colonia:</label>
      {{ form.colonia}}

      <label for="codigoPostal">Código Postal:</label>
      {{ form.codigoPostal}}

      <label for="calle">Calle:</label>
      {{ form.calle}}

      <label for="numExterior">Número Exterior:</label>
      {{ form.numExterior}}

      <label for="numInterior">Número Interior:</label>
      {{ form.numInterior}}

      <label for="entreCalle1">Entre calle 1:</label>
      {{ form.entreCalle1}}

      <label for="entreCalle2">Entre calle 2:</label>
      {{ form.entreCalle2}}

      <label for="nombreComplejo">Nombre Complejo:</label>
      {{ form.nombreComplejo}}
    </section>

    <!-- ######### seccion de la imagen ######## -->
    <section>
      <label for="imagen">Ingrese las imagenes de la vivienda:</label>
      {{ form.imagen}}
    </section>
    <button type="submit" class="button-primary">Guardar</button>
    <button class="button-primary" type='button' onclick='window.history.back()'>Cancelar</button>
  </form>
</div>
{% endblock %}